---
title: "US SARS-CoV-2 Variant Nowcast Hub weekly report"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(hubData)
library(ggplot2)
library(plotly)
library(crosstalk)
theme_set(theme_bw())

this_ref_date <- as.Date("2024-11-20")
quantiles <- c(0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95)
```


## Updates for `r this_ref_date`

The Variant Nowcast Hub collects new predictions weekly from participating teams.


## Plots

```{r}
## gather target data
target_data_filename <- paste0("https://covid-clade-counts.s3.amazonaws.com/", this_ref_date-2, "_covid_clade_counts.parquet")
target_data <- arrow::read_parquet(target_data_filename) |> 
  dplyr::filter(date >= this_ref_date - 150, ## fixing min date for plotting
                date <= this_ref_date - 40 ## fixing max date to remove under-reported recent data
                ) |> 
  dplyr::group_by(date) |> 
  tidyr::complete(location, clade, fill=list(count=0)) |> 
  dplyr::group_by(location, date) |> 
  dplyr::mutate(value = count/sum(count),
                total = sum(count))

## gather hub data
hub_con <- connect_hub(hub_path = "../variant-nowcast-hub/")
dat <- hub_con |> 
  dplyr::filter(nowcast_date == this_ref_date) |> 
  collect_hub()

mean_dat <- dat |> 
  dplyr::filter(output_type == "mean")

sample_dat <- dat |> 
  dplyr::filter(output_type == "sample")

quantile_data <- sample_dat |> 
  dplyr::group_by(model_id, target_date, location, clade) |> 
      dplyr::reframe(
        output_type_id = quantiles,
        value = stats::quantile(.data[["value"]], 
                                probs = quantiles, 
                                names = FALSE)
      )

# forecast_plot <- function(quantile_data, target_data, this_location = "MA") {
#   require(ggplot2)
#   require(plotly)
#   p <- ggplot() +
#     geom_line(data = dplyr::filter(quantile_data, output_type_id == 0.5, location == this_location),
#               aes(x=target_date, y=value, color=clade), linetype = 2) +
#     geom_point(data = dplyr::filter(target_data, location == this_location), 
#                aes(x=date, y=value, color=clade), alpha = 0.2) +
#     geom_smooth(data = dplyr::filter(target_data, location == this_location), 
#                 aes(x=date, y=value, color=clade, weight = total), se=FALSE) +
#     facet_wrap(.~model_id)
#   ggplotly(p)
# }


forecast_plot <- function(quantile_data, target_data) {
  require(ggplot2)
  require(plotly)
  p <- ggplot() +
    geom_line(data = dplyr::filter(quantile_data, output_type_id == 0.5),
              aes(x=target_date, y=value, color=clade), linetype = 2) +
    geom_point(data = dplyr::filter(target_data, location == "MA"), 
               aes(x=date, y=value, color=clade), alpha = 0.2) +
    geom_smooth(data = dplyr::filter(target_data, location == "MA"), 
                aes(x=date, y=value, color=clade, weight = total), se=FALSE) +
    facet_wrap(.~model_id)
  ggplotly(p)
}

```


```{r}
## adapted from https://stackoverflow.com/questions/72747650/r-make-boxplot-using-crosstalk-and-ggplot2-box-plot-color-is-lost

shared_quantile <- quantile_data |> 
  dplyr::filter(output_type_id == 0.5) |> 
  SharedData$new(~location, group = "Choose state")

shared_target <- target_data |> 
  SharedData$new(~location, group = "Choose state")

bscols(
  filter_select(id = "state", 
                label = "State", 
                sharedData = shared_quantile, 
                group = ~location,
                multiple = FALSE,
                allLevels = TRUE),
  ggplotly(
    ggplot() +
      geom_point(data = shared_quantile, 
                 aes(x=target_date, y=value, color=clade)) + 
      geom_point(data = shared_target,
                 aes(x=date, y=value, color=clade), alpha = 0.2) +
      # geom_smooth(data = shared_target, 
      #             aes(x=date, y=value, color=clade, weight = total),
      #             se=FALSE, method="gam") +
      facet_wrap(.~model_id)
  ),
  widths = 12
)
```

```{js}
// from https://stackoverflow.com/questions/67058016/how-to-set-default-values-in-filter-select-in-crosstalk-in-r-plotly
function filter_default() {
    document.getElementById("state").getElementsByClassName("selectized") 
[0].selectize.setValue("MA", false);
 }
window.onload = filter_default;
```

